services:
  base:
    build:
      context: ./docker/base
      tags:
        - "csc467:base"
    image: csc467:base

  master-instructor:
    build:
      context: ./docker/master-instructor
      tags:
        - "csc467:master-instructor"
    init: true
    image: csc467:master-instructor
    ports:
      - "18080:8080" # spark-master webui
      - "18088:8088" # code-server
      - "18888:8888" # jupyter server
    volumes:
      - ../courses:/lectures # courses is a github repo containing lecture materials
      - ./data:/data
      - ../grading-scripts:/grading-scripts
      - ../d2l:/d2l
    environment:
      - "SPARK_LOCAL_IP=spark-master"
    hostname: spark-master
    container_name: spark-master

  master-student:
    build:
      context: ./docker/master-student
      tags:
        - "csc467:master-student"
    init: true
    image: csc467:master-student
    ports:
      - "18888:8888" # jupyter server
      - "18080:8080" # spark-master webui
    volumes:
      - ./data:/data
    environment:
      - "SPARK_LOCAL_IP=spark-master"
    hostname: spark-master
    container_name: spark-master


  # This service will depend on either master-instructor or master-student    
  worker:
    build:
      context: ./docker/worker
      tags:
        - "csc467:worker"
    init: true
    image: csc467:worker
    ports:
      - "8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=128m
      - SPARK_EXECUTOR_MEMORY=256m
    volumes:
      - ./data:/data
      
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  17.18.0.0/16
