services:
  master:
    image: book-master:latest
    ports:
      - "8888:8888"
      - "8088:8088"
      - "8000:8000"
    volumes:
      - ../courses:/lectures # courses is a github repo containing lecture materials
      - ../csc467data:/data
      
  worker:
    image: book-worker:latest
    volumes:
      - ../courses:/lectures # courses is a github repo containing lecture materials
      - ../csc467data:/data
      
networks:
  default:
    driver: bridge
